// src/components/SaveableButtons.vue
<template>
  <div v-if="tracked">
    <button v-on:click="onSave" :disabled="!saveable">save</button>
    <button v-on:click="onRevert" :disabled="!saveable">revert</button>
    <button v-on:click="onDelete" :disabled="!deletable">delete</button>
  </div>
</template>

<script>
  import {saveable, save, revert, deleteModel, tracked, untrack} from '@/formState'
  export default {
    name: 'SaveableButtons'
    ,data () {
      return {
        saveable: false
        ,deletable: false
        ,tracked: true
      }
    }
    ,mounted(){
      saveable.add(isSaveable=>this.saveable = isSaveable)
      tracked.add((isTracked,isDeletable)=>{
        this.tracked = isTracked
        this.deletable = isDeletable
      })
    }
    ,methods: {
      onSave: save
      ,onRevert: revert
      ,onDelete: deleteModel
    }
  }
</script>

// src/app/component/saveable-buttons/saveable-buttons.component.ts
import {Component} from '@angular/core'
import {modelDirty, modelAction, modelAble} from '../../signals'

@Component({
  selector: 'app-saveable-buttons',
  templateUrl: './saveable-buttons.component.html'
})

export class SaveableButtonsComponent {

  isDeletable = false
  isSaveable = false
  isModelDirty = false

  constructor() {
    modelDirty.add(dirty=>{this.isModelDirty = dirty})
    modelAble.add(abilities=>{
      this.isDeletable = !!(modelAble.DELETE&abilities)
      this.isSaveable = !!(modelAble.SAVE&abilities)
    })
  }

  onSave(){ modelAction.dispatch(modelAction.SAVE) }

  onRevert(){ modelAction.dispatch(modelAction.REVERT) }

  onDelete(){ modelAction.dispatch(modelAction.DELETE) }
}

<span>
  <button *ngIf="isSaveable" (click)="onSave()" [disabled]="!isModelDirty" class="btn-primary">save</button>
  <button *ngIf="isSaveable" (click)="onRevert()" [disabled]="!isModelDirty" class="btn-primary">revert</button>
  <button *ngIf="isDeletable" (click)="onDelete()" class="btn-warning">delete</button>
</span>
