// src/views/Project.vue
<template>
  <div>
    <button v-on:click="clone(project)" class="float-right">clone</button>
    <h1>Project: {{project.description}}</h1>
    <section>
      <dl>
        <dt data-appExplain="'project.client'">client</dt>
        <dd><router-link class="input" v-bind:to="client.uri||''">{{client.name}}</router-link></dd>
        <dt data-appExplain="'project.description'">description</dt>
        <dd><input v-model="project.description"/></dd>
        <dt data-appExplain="'project.invoiceNr'">invoice number</dt>
        <dd><div class="input mono">{{project.invoiceNr}}</div></dd>
        <dt data-appExplain="'project.hourlyRate'">hourly rate</dt>
        <dd class="hourly-rate">
          <currency :value="project.hourlyRateCalculated" class="text-align-left"/>
          <input v-model.number="project.hourlyRate" type="number"/>
        </dd>
        <dt data-appExplain="'project.discount'">discount</dt>
        <dd><input v-model="project.discount" type="number"/></dd>
        <dt data-appExplain="'project.discountRate'">discounted rate</dt>
        <dd><currency :value="project.hourlyRate - project.hourlyRate*project.discount*0.01" class="text-align-left"/></dd>
        <dt data-appExplain="'project.paid'">paid</dt>
        <dd><label class="checkbox"><input v-model="project.paid" type="checkbox"/><span></span></label></dd>
      </dl>
    </section>
    
    <section>
      <button v-on:click="onAddLine()" class="float-right">add line</button>
      <h3>lines</h3>
      <table>
        <thead>
        <tr>
          <th width="60%">description</th>
          <th width="5%"><span class="hidden-xs-down">hours</span></th>
          <th></th>
          <th>amount</th>
          <th>VAT</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(line, index) in project.lines" :key="index">
          <td><input v-model="line.description"/></td>
          <td><input v-model.number="line.hours" type="number"/></td>
          <td><currency @click.native="onClickLineCalculation(project,line)" :value="line.hours*project.hourlyRateDiscounted"/></td>
          <td><input v-model.number="line.amount" type="number" step="0.01"/></td>
          <td>
            <select v-model="line.vat" class="mono">
              <option v-for="vat in vatAmounts" v-bind:key="vat" v-bind:value="vat">{{vat}}</option>
            </select>
          </td>
          <td><button v-on:click="onRemoveLine(line)">&#10006;</button></td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
          <td>total ex VAT</td>
          <td>
            <div class="input mono">{{project.totalHours}}</div>
          </td>
          <td><currency :value="project.totalHours*project.hourlyRateDiscounted"/></td>
          <td><currency :value="project.total"/></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>total inc VAT</td>
          <td></td>
          <td></td>
          <td><currency :value="project.totalIncDiscounted"/></td>
          <td></td>
          <td></td>
        </tr>
        </tfoot>
      </table>
    </section>
    
    <section>
      <header class="clearfix">
        <button data-ngClick="onAddInvoice()" class="float-right">add invoice</button>
        <h3>invoices</h3>
      </header>
      <ul class="list-unstyled">
        <li v-for="(invoice, i) in project.invoices" v-bind:key="i" class="row">
          <div class="col-3"></div>
          <div class="col-3 col-md-2">
            <a v-bind:href="`${project.uri}/${invoice.type}${i!==0?'/'+i:''}`" class="btn">{{invoice.type}}{{i!==0?'&nbsp;' + i:''}}</a>
          </div>
          <div class="col-2 col-md-3"><input v-model="invoice.date" type="date"/></div>
          <div class="col-2 col-md-2 text-align-right">
            <label v-if="i>0" class="checkbox"><input v-model="invoice.interest" type="checkbox"/><span title="add interest"></span></label>
            <label v-if="i>1" class="checkbox"><input v-model="invoice.exhortation" type="checkbox"/><span title="exhortation"></span></label>
          </div>
          <div class="col-2 col-md-5 text-align-right">
            <button data-ngClick="onRemoveInvoice(invoice)">&#10006;</button>
          </div>
        </li>
      </ul>
    </section>
    
    <section>
      <a v-bind:href="`${project.uri}/quotation`" class="btn float-right">show quotation</a>
      <h3>quotation</h3>
      <dl>
        <dt data-appExplain="'project.quotationBefore'">quotation before</dt>
        <dd><textarea v-model="project.quotationBefore"></textarea></dd>
        <dt data-appExplain="'project.quotationAfter'">quotation after</dt>
        <dd><textarea v-model="project.quotationAfter"></textarea></dd>
        <dt data-appExplain="'project.quotationDate'">quotation date</dt>
        <dd><input v-model="project.quotationDate" type="date"/></dd>
      </dl>
    </section>
  </div>
</template>

<script>
import model from '@/model'
import Currency from '@/components/Currency.vue'
import signals from '@/signals'
import {track,save} from '@/formState'

const INVOICE = {VAT_DEFAULT:21} // todo:fix to somewhere

export default {
  name: 'project'
  ,data () {
    return {
      client:{}
      ,project:{}
      ,vatAmounts: model.personal.vatAmounts.split(/,/g).map(parseFloat)
    }
  }
  ,components: {
    Currency
  }
  ,mounted(){
    this.client = model.getClientByNr(parseInt(this.$route.params.clientNr,10))
    //
    const project = this.client.projects[parseInt(this.$route.params.projectIndex,10)]
    const projectClone = project.clone()
    this.project = projectClone
    track(this.$el,project,projectClone,this.deleteProject)
  },
  methods: {
    onRemoveLine(line) {
      const lines = this.project.lines,
          i = lines.indexOf(line)
      i!==-1&&lines.splice(i, 1)
    },
    onAddLine(){
      this.project.addLine()
    },
    onClickLineCalculation(project, line) {
      line.amount = line.hours*project.hourlyRateDiscounted
    },
    clone(project) {
      console.log('clonedProject',JSON.parse(JSON.stringify(project))); // todo: remove log
      //const clonedProject = this.modelService.cloneProject(project)
      //this.router.navigate([clonedProject.uri])
    },
    deleteProject() {
      const project = this.client.projects[parseInt(this.$route.params.projectIndex,10)]
      confirm('Delete this project?') && this.client.deleteProject(project) && (save(),this.$router.push(this.client.uri))
    }
  }
}
</script>

// src/app/page/project/project.component.ts
import {Component, OnInit, OnDestroy} from '@angular/core'
import {Router, ActivatedRoute} from '@angular/router'
import {Client} from '../../model/client'
import {IProject} from '../../interface/project'
import {IInvoice} from '../../interface/invoice'
import {IInvoiceLine} from '../../interface/invoice-line'
import {ModelService} from '../../model/model.service'
import {Saveable} from '../../abstract/saveable'
import {dateTimeToDate} from '../../mixins'
import {modelAction, modelAble} from '../../signals'
import {Project} from '../../model/project'
import {ExplainDirective} from '../../directive/explain.directive'

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss']
})

export class ProjectComponent extends Saveable implements OnInit, OnDestroy {

  static data:any = {
    title: 'Project',
    heading: 'Project',
    meta: {description: 'Foo is the bar of all qux'},
    declarations: [ExplainDirective]
  }
  private subscription:any
  private projectProper:Project

  public client:Client
  public project:Project
  public personal:any

  name:Function

  constructor(
      protected modelService:ModelService,
      private router:Router,
      private route:ActivatedRoute
  ) {
    super(modelService, modelAble.SAVE|modelAble.DELETE)
    modelAction.add(state=>{
      state===modelAction.DELETE&&this.onDelete()
    })
  }

  ngOnInit() {
    super.ngOnInit()
    this.subscription = this.route.params.subscribe(params=> {
      const clientNr:number = params['clientNr']<<0
      const projectIndex:number = (params['projectIndex']<<0) - 1
      //
      this.client = this.modelService.getClientByNr(clientNr)
      this.projectProper = this.modelService.getProject(clientNr, projectIndex)
      this.personal = this.modelService.getPersonal()
      //
      if (!this.projectProper) {
        this.router.navigate([(this.client as Client).uri])
      } else {
        this.project = this.setModel(this.projectProper)
      }
    })
  }

  ngOnDestroy() {
    super.ngOnDestroy()
    this.subscription.unsubscribe()
  }

  protected onDelete():boolean {
    let isDeleted = super.onDelete(this.modelService.removeProject.bind(this.modelService))
    isDeleted&&this.router.navigate([this.client.uri])
    return isDeleted
  }

  clone(project:IProject) {
    const clonedProject = this.modelService.cloneProject(project)
    this.router.navigate([clonedProject.uri])
  }

  onRemoveLine(line:IInvoiceLine) {
    let lines = this.project.lines,
        i = lines.indexOf(line)
    i!==-1&&lines.splice(i, 1)
    this.checkModelDirty()
  }

  onAddLine() {
    this.project.lines.push(<IInvoiceLine>{amount:0, hours:0, vat:this.vatAmounts.slice(0).shift()})
    this.checkModelDirty()
  }

  onAddInvoice() {
    let invoices = this.project.invoices
    invoices.push(<IInvoice>{
      date: dateTimeToDate(),
      type: this.project.invoices.length===0?'invoice':'reminder', // todo: from const
      interest: false,
      exhortation: false
    })
    this.onSave()
    this.checkModelDirty()
  }

  onRemoveInvoice(invoice:IInvoice) {
    let invoices = this.project.invoices,
        i = invoices.indexOf(invoice)
    i!==-1&&invoices.splice(i, 1)
    this.checkModelDirty()
  }

  onClickCalculation(project:Project, line:IInvoiceLine) {
    line.amount = line.hours*project.hourlyRateDiscounted
    this.checkModelDirty()
  }

  protected cloneModel():any {
    this.project = super.cloneModel() as Project
    return this.project
  }

  get vatAmounts():number[] {
    return this.personal.vatAmounts.split(/,/g).map(vat=>parseFloat(vat))
  }
}

<div *ngIf="project">
  <button (click)="clone(project)" class="btn-default float-right">clone</button>
  <h2>{{project?.description}}</h2>
  <section>
    <dl class="row">
      <dt [appExplain]="'project.client'">client</dt><dd><a routerLink="/client/{{client?.nr}}">{{client?.name}}</a></dd>
      <dt [appExplain]="'project.description'">description</dt><dd><input [(ngModel)]="project.description" (ngModelChange)="onNgModelChanged()" /></dd>
      <dt [appExplain]="'project.invoiceNr'">invoice number</dt><dd>{{project?.invoiceNr}}</dd>
      <dt [appExplain]="'project.hourlyRate'">hourly rate</dt><dd><input [(ngModel)]="project.hourlyRate" (ngModelChange)="onNgModelChanged()" type="number" /></dd>
      <dt [appExplain]="'project.discount'">discount</dt><dd><input [(ngModel)]="project.discount" (ngModelChange)="onNgModelChanged()" type="number" /></dd>
      <dt [appExplain]="'project.discountRate'">discounted rate</dt><dd>{{project.hourlyRate - project.hourlyRate*project.discount*0.01 | number : '1.2-2'}}</dd>
      <dt [appExplain]="'project.paid'">paid</dt><dd><label class="checkbox"><input [(ngModel)]="project.paid" type="checkbox" (ngModelChange)="onNgModelChanged()" /><span></span></label></dd>
    </dl>
  </section>
  
  <section>
    <button (click)="onAddLine()" class="btn-primary float-right">add line</button>
    <h3>lines</h3>
    <table>
      <thead><tr>
        <th>description</th>
        <th><span class="hidden-xs-down">hours</span><span class="hidden-sm-up">hrs</span></th>
        <th></th>
        <th>amount</th>
        <th>VAT</th>
        <th></th>
      </tr></thead>
      <tbody><tr *ngFor="let line of project?.lines">
        <td><input [(ngModel)]="line.description" (ngModelChange)="onNgModelChanged()" /></td>
        <td><input [(ngModel)]="line.hours" (ngModelChange)="onNgModelChanged()" type="number" /></td>
        <td><small (dblclick)="onClickCalculation(project,line)"><app-currency [amount]="line.hours*project.hourlyRateDiscounted"></app-currency></small></td>
        <td><input [(ngModel)]="line.amount" (ngModelChange)="onNgModelChanged()" type="number" /></td>
        <td>
          <select [(ngModel)]="line.vat" (ngModelChange)="onNgModelChanged()">
            <option *ngFor="let vat of vatAmounts" [value]="vat">{{vat}}</option>
          </select>
        </td>
        <td><button (click)="onRemoveLine(line)" class="btn-default">&#10006;</button></td>
      </tr></tbody>
      <tfoot><tr>
        <td><strong>total ex VAT</strong></td>
        <td>{{project.totalHours}}</td>
        <td><small><app-currency [amount]="project.totalHours*project.hourlyRateDiscounted"></app-currency></small></td>
        <td><app-currency [amount]="project.total"></app-currency></td>
        <td></td>
        <td></td>
      </tr><tr>
        <td><strong>total inc VAT</strong></td>
        <td></td>
        <td></td>
        <td><app-currency [amount]="project.totalIncDiscounted"></app-currency></td>
        <td></td>
        <td></td>
      </tr></tfoot>
    </table>
  </section>
  
  <section>
    <button (click)="onAddInvoice()" class="btn-primary float-right">add invoice</button>
    <h3>invoices</h3>
    <ul class="list-unstyled">
      <li *ngFor="let invoice of project?.invoices; let i = index" class="row">
        <div class="col-3 col-md-3"><input [(ngModel)]="invoice.date" (ngModelChange)="onNgModelChanged()" type="date" /></div>
        <div class="col-3 col-md-2"><a routerLink="{{project.uri}}/{{invoice.type}}{{i!==0?'/'+i:''}}" class="btn btn-sm btn-primary">{{invoice.type}} {{i!==0?i:''}}</a></div>
        <div class="col-4 col-md-2 form-inline">
          <label *ngIf="i>0" class="checkbox"><input [(ngModel)]="invoice.interest" type="checkbox" /><span title="add interest"></span></label>
          <label *ngIf="i>1" class="checkbox"><input [(ngModel)]="invoice.exhortation" type="checkbox" /><span title="exhortation"></span></label>
        </div>
        <div class="col-2 col-md-5"><button (click)="onRemoveInvoice(invoice)" class="btn-default">&#10006;</button></div>
      </li>
    </ul>
  </section>
  
  <section>
    <a routerLink="{{project.uri}}/quotation" class="btn btn-sm btn-primary float-right">show quotation</a>
    <h3>quotation</h3>
    <dl class="row">
      <dt class="col-6" [appExplain]="'project.quotationBefore'">quotation before</dt><dd class="col-6"><textarea [(ngModel)]="project.quotationBefore"></textarea></dd>
      <dt class="col-6" [appExplain]="'project.quotationAfter'">quotation after</dt><dd class="col-6"><textarea [(ngModel)]="project.quotationAfter"></textarea></dd>
      <dt class="col-6" [appExplain]="'project.quotationDate'">quotation date</dt><dd class="col-6"><input [(ngModel)]="project.quotationDate" (ngModelChange)="onNgModelChanged()" type="date" /></dd>
    </dl>
  </section>
</div>
