// src/views/Client.vue
<template>
  <div>
    <h1>Client: {{client.name}}</h1>
    <section>
      <dl>
        <dt>name</dt><dd><input v-model="client.name"/></dd>
        <dt>nr</dt><dd><input v-model="client.nr"/></dd>
        <dt>address</dt><dd><input v-model="client.address"/></dd>
        <dt>city</dt><dd><input v-model="client.city"/></dd>
        <dt>contact</dt><dd><input v-model="client.contact"/></dd>
        <dt>paymentterm</dt><dd><input v-model="client.paymentterm"/></dd>
        <dt>phone</dt><dd><input v-model="client.phone"/></dd>
        <dt>postbox</dt><dd><input v-model="client.postbox"/></dd>
        <dt>zipcode</dt><dd><input v-model="client.zipcode"/></dd>
        <dt>zippost</dt><dd><input v-model="client.zippost"/></dd>
      </dl>
    </section>
    
    <section>
      <header class="clearfix">
        <button v-on:click="onAddProject()" class="float-right">add project</button>
        <h3>Projects</h3>
      </header>
      <project-list :projects="client.projects"></project-list>
    </section>
  </div>
</template>

<script>
import model from '@/model'
import {track,untrack,save} from '@/formState'
import {create} from '@/model/project'
import ProjectList from '../components/ProjectList'

export default {
  name: 'client'
  ,data () {
    return {
      client:{}
    }
  }
  ,mounted(){
    const client = model.getClientByNr(parseInt(this.$route.params.clientNr,10))
    const clientClone = client.clone()
    this.client = clientClone
    track(this.$el,client,clientClone,this.deleteClient)
  }
  ,components: {ProjectList}
  ,destroyed: untrack
  ,methods: {
    onAddProject(){
      const project = this.client.createProject()
      project && save()
      this.$router.push(project.uri)
    }
    ,deleteClient(){
      const client = model.getClientByNr(parseInt(this.$route.params.clientNr,10))
      confirm('Delete this client?') && model.deleteClient(client) && (save(),this.$router.push('/clients'))
    }
  }
}
</script>

// src/app/page/client/client.component.ts
import {Component, OnInit, OnDestroy} from '@angular/core'
import {Router, ActivatedRoute} from '@angular/router'
import {IClient} from '../../interface/client'
import {Saveable} from '../../abstract/saveable'
import {ModelService} from '../../model/model.service'
import {modelAction, modelAble} from '../../signals'

@Component({
  selector: 'app-client',
  templateUrl: './client.component.html',
  styleUrls: ['./client.component.scss']
})

export class ClientComponent extends Saveable implements OnInit, OnDestroy {

  static data:any = {
    title: 'Client',
    heading: 'Client',
    meta: {description: 'Foo is the bar of all qux'}
  }
  private subscription:any
  public client:IClient
  public clientNr:number

  constructor(
    protected modelService:ModelService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    super(modelService, modelAble.SAVE|modelAble.DELETE)
    modelAction.add(state=>{
      state===modelAction.DELETE&&this.onDelete()
    })
  }

  ngOnInit() {
    super.ngOnInit()
    this.subscription = this.route.params.subscribe(params => {
       this.clientNr = params['clientNr']<<0
    this.client = this.setModel(this.modelService.getClientByNr(this.clientNr)) as IClient
    })
  }

  ngOnDestroy() {
    super.ngOnDestroy()
    this.subscription.unsubscribe()
  }

  onDelete() {
    let isDeleted:boolean = super.onDelete(this.modelService.removeClient.bind(this.modelService))
    isDeleted&&this.router.navigate(['/clients'])
    return isDeleted
  }

  onAddProject() {
    let project = this.modelService.addProject(this.clientNr)
    this.router.navigate([project.uri])
  }

  protected cloneModel():IClient {
    this.client = super.cloneModel() as IClient
    return this.client
  }

}

<h2>{{client?.name}}</h2>

<section>
  <dl class="row">
    <dt class="col-3 text-right">name</dt><dd class="col-9"><input [(ngModel)]="client.name" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">address</dt><dd class="col-9"><input [(ngModel)]="client.address" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">city</dt><dd class="col-9"><input [(ngModel)]="client.city" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">contact</dt><dd class="col-9"><input [(ngModel)]="client.contact" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">nr</dt><dd class="col-9"><input [(ngModel)]="client.nr" (ngModelChange)="onNgModelChanged()" type="number" /></dd>
    <dt class="col-3 text-right">paymentterm</dt><dd class="col-9"><input [(ngModel)]="client.paymentterm" (ngModelChange)="onNgModelChanged()" type="number" /></dd>
    <dt class="col-3 text-right">phone</dt><dd class="col-9"><input [(ngModel)]="client.phone" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">postbox</dt><dd class="col-9"><input [(ngModel)]="client.postbox" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">zipcode</dt><dd class="col-9"><input [(ngModel)]="client.zipcode" (ngModelChange)="onNgModelChanged()" /></dd>
    <dt class="col-3 text-right">zippost</dt><dd class="col-9"><input [(ngModel)]="client.zippost" (ngModelChange)="onNgModelChanged()" /></dd>
  </dl>
</section>

<section class="clearfix">
  <div class="clearfix">
    <h2 class="float-left">projects</h2>
    <button (click)="onAddProject()" class="btn-primary float-right">add project</button>
  </div>
  <ul class="list-unstyled">
    <li *ngFor="let project of client?.projects">
      <a routerLink="{{project.uri}}">{{project.invoiceNr}} {{project.description}}</a>
    </li>
  </ul>
</section>
