// src/app/page/quarter/quarter.component.ts
import {Component, OnInit, ViewChild, ElementRef} from '@angular/core'
import {ActivatedRoute} from '@angular/router'
import {InterpolationService} from '../../service/interpolation.service'
import {ModelService} from '../../model/model.service'
import {Project} from '../../model/project'
import {IProject} from '../../interface/project'
import {INVOICE} from '../../config/invoice'
import {CurrencyFormat} from '../../filter/currency-format.pipe'

@Component({
  selector: 'app-quarter',
  templateUrl: './quarter.component.html',
  styleUrls: ['./quarter.component.scss']
})

export class QuarterComponent implements OnInit {

  static data:any = {
    title: 'Quarter',
    heading: 'Quarter',
    meta: {description: 'Welcome to Quarter'}
  }

  private projects:Project[]
  private csvTemplate = ''
  @ViewChild('csv') private csvRef:ElementRef
  private elmCsv:HTMLTextAreaElement

  quarters:IProject[][] = [[], [], [], []]
  year = (new Date).getFullYear()
  years = []
  dateFormat:string = INVOICE.dateFormat

  constructor(
    public modelService:ModelService,
    protected interpolationService:InterpolationService,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      if (params.hasOwnProperty('year')){
        this.year = parseInt(params['year'], 10)
        this.setQuarters()
      }
    })
    const config:any = this.modelService.getConfig()
    this.csvTemplate = config.csvTemplate
    this.projects = this.modelService.getProjects().slice(0)
    this.setQuarters()
    this.years = this.projects.filter(project=>project.invoices.length).map((project:Project)=>{
      return project.year
    }).filter((elem, pos, arr) => {
      return arr.indexOf(elem)===pos
    }).sort()
    this.elmCsv = this.csvRef.nativeElement
    //
    // this.quarters.forEach(quarter=>{
    //   const arr = quarter as any
    //   // arr.totalDiscounted = quarter.map(project=>project.totalDiscounted).reduce((a, b)=>a+b)
    //   // arr.totalVatDiscounted = quarter.map(project=>project.totalVatDiscounted).reduce((a, b)=>a+b)
    //   // arr.totalIncDiscounted = quarter.map(project=>project.totalIncDiscounted).reduce((a, b)=>a+b)
    //   Object.defineProperty(arr, 'totalDiscounted', { set: function() { return this.quarter.map(project=>project.totalDiscounted).reduce((a, b)=>a+b); } });
    //   Object.defineProperty(arr, 'totalVatDiscounted', { set: function() { return this.quarter.map(project=>project.totalVatDiscounted).reduce((a, b)=>a+b); } });
    //   Object.defineProperty(arr, 'totalIncDiscounted', { set: function() { return this.quarter.map(project=>project.totalIncDiscounted).reduce((a, b)=>a+b); } });
    // })
  }

  private setQuarters(){
    this.quarters.forEach(quarter=>{
      quarter.length = 0
    })
    this.projects&&this.projects
        .filter(project=>project.invoices.length&&project.year===this.year)
        .forEach((project:Project)=>{
          const monthNumber = project.date.getMonth()
          const quarter = Math.ceil((monthNumber+1)/3)
          this.quarters[quarter-1].push(project)
        })
  }

  onClickCsv(quarter:IProject[]) {
    const parsed = quarter.map(project=>{
      const client = (project as Project).client,
        invoice = project.invoices.slice(0).shift(),
        currencyPipe = new CurrencyFormat(),
        data = this.modelService.getData().personal,
        currency = (...args) => currencyPipe.transform.apply(currencyPipe, args)
      return this.interpolationService.parse(this.csvTemplate, {
        project,
        client,
        invoice,
        data,
        currency
      })
    })
    this.elmCsv.value = parsed.join('\n')
    if (this.elmCsv && this.elmCsv.select) {
      this.elmCsv.select()
      try {
        document.execCommand('copy')
        this.elmCsv.blur()
      } catch (err) {
        alert('please press Ctrl/Cmd+C to copy')
      }
    }
  }

  getTotalDiscounted(quarter?:Project[]):number {
    let total = 0
    if (quarter===undefined) {
      quarter = this.projects&&this.projects
        .filter(project=>project.invoices.length&&project.year===this.year)
    }
    quarter
        .forEach((project:Project)=>{
          total += project.totalDiscounted
        })
    return total
  }

  getTotalVatDiscounted(quarter?:Project[]):number {
    let total = 0
    if (quarter===undefined) {
      quarter = this.projects&&this.projects
        .filter(project=>project.invoices.length&&project.year===this.year)
    }
    quarter
        .forEach((project:Project)=>{
          total += project.totalVatDiscounted
        })
    return total
  }

  getTotalIncDiscounted(quarter?:Project[]):number {
    let total = 0
    if (quarter===undefined) {
      quarter = this.projects&&this.projects
        .filter(project=>project.invoices.length&&project.year===this.year)
    }
    quarter
        .forEach((project:Project)=>{
          total += project.totalIncDiscounted
        })
    return total
  }

}

<header>
  <nav>
    <ul class="list-unstyled list-inline">
      <li class="list-inline-item {{y===year?'current':''}}" *ngFor="let y of years"><a routerLink="/overview/quarter/{{y}}">{{y}}</a></li>
    </ul>
  </nav>
</header>
<section *ngFor="let quarter of quarters; let i = index">
  <h3 class="float-left">quarter {{i+1}}</h3>
  <button (click)="onClickCsv(quarter)" class="btn btn-secondary float-right">copy csv data</button>
  <table>
    <thead><tr>
      <th width="10%" data-order-key="invoiceNr">nr</th>
      <th width="10%" data-order-key="date">date</th>
      <th width="20%" data-order-key="client">client</th>
      <th width="33%" data-order-key="description">description</th>
      <th width="9%" data-order-key="totalDiscounted" class="text-right">ex</th>
      <th width="9%" data-order-key="totalVatDiscounted" class="text-right">VAT</th>
      <th width="9%" data-order-key="totalIncDiscounted" class="text-right">total</th>
    </tr></thead><tbody>
      <tr *ngFor="let project of quarter | arraySort:'date'" class="row-select">
        <td><a routerLink="{{project.uri}}">{{project.invoiceNr}}</a></td>
        <td><small>{{project.date | date:dateFormat}}</small></td>
        <td class="text-overflow">{{project.client.name}}</td>
        <td class="text-overflow">{{project.description}}</td>
        <td class="text-right">{{project.totalDiscounted | currency:'EUR':true}}</td>
        <td class="text-right">{{project.totalVatDiscounted | currency:'EUR':true}}</td>
        <td class="text-right">{{project.totalIncDiscounted | currency:'EUR':true}}</td>
      </tr>
    </tbody>
    <tfoot>
      <tr class="row-select">
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right">{{getTotalDiscounted(quarter) | currency:'EUR':true}}</td>
        <td class="text-right">{{getTotalVatDiscounted(quarter) | currency:'EUR':true}}</td>
        <td class="text-right">{{getTotalIncDiscounted(quarter) | currency:'EUR':true}}</td>
      </tr>
    </tfoot>
  </table>
</section>
<section>
  <table>
    <thead><tr>
      <th width="10%"></th>
      <th width="10%"></th>
      <th width="35%"></th>
      <th width="40%"></th>
      <th data-order-key="totalDiscounted" class="text-right" width="10%">ex</th>
      <th data-order-key="totalVatDiscounted" class="text-right" width="10%">VAT</th>
      <th data-order-key="totalIncDiscounted" class="text-right" width="10%">total</th>
    </tr></thead><tbody>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right">{{getTotalDiscounted() | currency:'EUR':true}}</td>
        <td class="text-right">{{getTotalVatDiscounted() | currency:'EUR':true}}</td>
        <td class="text-right">{{getTotalIncDiscounted() | currency:'EUR':true}}</td>
      </tr>
    </tbody>
  </table>
</section>
<textarea #csv class="visually-hidden"></textarea>

// src/views/Quarter.vue
<template>
  <div class="page-quarter">
    <header>
      <nav>
        <ul class="list-unstyled list-inline">
          <li v-for="y in years" v-bind:class="{current:y===year}"><router-link v-bind:to="`/overview/quarter/${y}`">{{y}}</router-link></li>
        </ul>
      </nav>
    </header>
    <section v-for="(quarter, i) in quarters" :key="i">
      <h3 class="float-left">quarter {{i+1}}</h3>
      <button data-ngClick="onClickCsv(quarter)" class="btn btn-secondary btn-sm float-right">copy csv data</button>
      <project-list :projects="quarter" :cols="'invoiceNr date clientName description totalDiscounted totalVatDiscounted totalIncDiscounted'"></project-list>
      <textarea class="visually-hidden"></textarea>
    </section>
  </div>
</template>

<script>
import model from '@/model'
import Currency from '@/components/Currency'
import ProjectList from '@/components/ProjectList'
export default {
  name: 'quarter'
  ,data () {
    return {
      projects: []
      ,year: new Date().getFullYear()
      ,years: []
      ,quarters: [[], [], [], []]
      ,csvTemplate: ''
      ,elmCsv: document.createElement('div')
    }
  }
  ,components: {
    Currency
    ,ProjectList
  }
  ,mounted(){
    this.csvTemplate = model.config.csvTemplate
    this.projects = model.projects
    
    this.year = parseInt(this.$route.params.year,10)||this.year
    this.years = this.projects
        .filter(project=>project.invoices.length)
        .map(project=>project.year)
        .filter((elem, pos, arr) => arr.indexOf(elem)===pos)
        .sort()
    
    this.setQuarters()
  }
  ,watch: {
    '$route'() {
      this.year = parseInt(this.$route.params.year,10)||this.year
      this.setQuarters()
    }
  }
  ,methods: {
    
    setQuarters(){
      this.quarters.forEach(quarter=>quarter.length = 0)
      this.projects
          .filter(project=>project.invoices.length&&project.year===this.year)
          .forEach(project=>{
            const monthNumber = project.date.getMonth()
            const quarter = Math.ceil((monthNumber+1)/3)
            this.quarters[quarter-1].push(project)
          })
    }
  
    ,onClickCsv(quarter) {
      const parsed = quarter.map(project=>{
        const client = project.client,
          invoice = project.invoices.slice(0).shift(),
          currencyPipe = new CurrencyFormat(),
          data = this.modelService.getData().personal,
          currency = (...args) => currencyPipe.transform.apply(currencyPipe, args)
        return this.interpolationService.parse(this.csvTemplate, {
          project,
          client,
          invoice,
          data,
          currency
        })
      })
      this.elmCsv.value = parsed.join('\n')
      if (this.elmCsv && this.elmCsv.select) {
        this.elmCsv.select()
        try {
          document.execCommand('copy')
          this.elmCsv.blur()
        } catch (err) {
          alert('please press Ctrl/Cmd+C to copy')
        }
      }
    }
    
    
  }
}
</script>

<style type="scss">
  .current { font-weight: bold; }
  .page-quarter.page-quarter .alert-paid, .page-quarter.page-quarter .alert-paid * { color: inherit; }
  /*.page-quarter.page-quarter.page-quarter .alert {
    &-paid { &, * { color: inherit; }}
    &-late { &, * { color: inherit; }}
    &-pending { &, * { color: inherit; }}
    &-select { &, * { background-color: inherit; }}
  }*/
</style>
