// src/app/page/settings/settings.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core'
import {ModelService} from '../../model/model.service'
import {Saveable} from '../../abstract/saveable'
import {IConfig} from '../../interface/config'
import {IData} from '../../interface/store-data'

import {IClient} from '../../interface/client'
import {Client} from '../../model/client'
import {Project} from '../../model/project'
import * as dummyData from '../../dummy/data'
import {sassChanged} from '../../signals'
import {ExplainDirective} from '../../directive/explain.directive'
import {CURRENCY_ISO} from '../../config/currencyISO'
// import { PatternValidator } from '@angular/forms'

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})

export class SettingsComponent extends Saveable implements OnInit, OnDestroy {

  static data:any = {
    title: 'Settings',
    heading: 'Settings',
    meta: {robots: 'noindex, nofollow'},
    declarations: [ExplainDirective]
  }

  settings:any
  client:any
  project:any
  invoice:any
  currencies:any[]

  constructor(
      protected modelService:ModelService
  ) {
    super(modelService)
    // this.currencies = CURRENCY_ISO
    this.currencies = Object.keys(CURRENCY_ISO).map(key=>CURRENCY_ISO[key])
  }

  ngOnInit() {
    super.ngOnInit()
    this.settings = this.setModel(this.modelService.getConfig())
    //
    const client = new Client(<IClient>dummyData.default.clients[0])
    client.projects = client&&client.projects.map(project=>new Project(project, client, this.modelService))
    this.client = client
    this.project = client&&client.projects.slice(0).pop()
    this.invoice = this.project.invoices.slice(0).shift()
    sassChanged.dispatch(this.settings.invoiceCSS)
    setTimeout(sassChanged.dispatch.bind(sassChanged, this.settings.invoiceCSS))
  }

  ngOnDestroy(){
    sassChanged.dispatch()
  }

  onClickDownload(e:Event, type:string){
    let currentTarget:HTMLElement = <HTMLElement>e.currentTarget,
        isConfig = type==='config',
        dataString:string = isConfig?this.modelService.getStoreableConfig():this.modelService.getStoreableData()
    currentTarget.setAttribute('href', `data:text/json,${encodeURIComponent(dataString)}`)
    currentTarget.setAttribute('download', `${type}.json`)
  }

  onChangeRestore(e:any, type:string){
    const target = e.target
    const fileReader = new FileReader()
    const file = target.files[0]
    fileReader.readAsText(file)
    fileReader.addEventListener('load', ()=>{
      const result = fileReader.result,
          resultData = JSON.parse(result)
      if (resultData.type===type) {
        delete resultData.type
        if (type==='config') {
          this.settings = this.setModel(this.modelService.setConfig(<IConfig>resultData))
        } else if (type==='data') {
          this.modelService.setData(<IData>resultData)
        }
      }
      target.value = null
    })
  }

  onClickClear(type:string){
    if (confirm(`Do you really want to clear the ${type}?`)) {
      type==='config'?this.modelService.clearConfig():this.modelService.clearData()
    }
  }

  onRevert(){
    super.onRevert()
    sassChanged.dispatch()
  }

  protected cloneModel():any {
    return this.settings = <any>super.cloneModel()
  }

}

<section>
  <dl class="row">
    <dt [appExplain]="'settings.backup'" class="name">backup</dt>
    <dd>
      <a (click)="onClickDownload($event,'config')" class="btn btn-secondary btn-sm" href="#">config</a>
      <a (click)="onClickDownload($event,'data')" class="btn btn-secondary btn-sm" href="#">data</a>
    </dd>
    <dt [appExplain]="'settings.restore'" class="name">restore</dt>
    <dd>
      <label class="btn btn-secondary btn-sm" for="config">config</label><input accept="application/json, text/json, .json" type="file" id="config" (change)="onChangeRestore($event,'config')" class="visually-hidden" />
      <label class="btn btn-secondary btn-sm" for="data">data</label><input accept="application/json, text/json, .json" type="file" id="data" (change)="onChangeRestore($event,'data')" class="visually-hidden" />
    </dd>
    <dt [appExplain]="'settings.clear'" class="name">clear</dt>
    <dd>
      <button (click)="onClickClear('config')" class="btn btn-secondary btn-sm">config</button>
      <button (click)="onClickClear('data')" class="btn btn-secondary btn-sm">data</button>
    </dd>
  </dl>
</section>
<section>
  <dl class="row">
    <dt [appExplain]="'settings.projectNumberTemplate'" class="name">projectNumberTemplate</dt><dd>
      <app-interpolationui [(ngModel)]="settings.projectNumberTemplate" (ngModelChange)="onNgModelChanged()"></app-interpolationui>
    </dd>
    <dt [appExplain]="'settings.csvTemplate'" class="name">csvTemplate</dt><dd>
      <app-interpolationui [(ngModel)]="settings.csvTemplate" (ngModelChange)="onNgModelChanged()"></app-interpolationui>
    </dd>
    <dt [appExplain]="'settings.langs'" class="name">langs</dt><dd>
      <input type="text" pattern="\w\w(,\w\w)*" rows="4" [(ngModel)]="settings.langs" (ngModelChange)="onNgModelChanged()" />
    </dd>
    <dt [appExplain]="'settings.currency'" class="name">currency</dt><dd>
      <select [(ngModel)]="settings.currency" (ngModelChange)="onNgModelChanged()">
        <option *ngFor="let currency of currencies" value="{{currency.code}}" ngDefaultControl>{{currency.name}} ({{currency.symbol}})</option>
      </select>
    </dd>
    <dt [appExplain]="'settings.homeMessage'" class="name">welcome message</dt><dd>
      <input type="checkbox" [(ngModel)]="settings.homeMessage" (ngModelChange)="onNgModelChanged()" />
    </dd>
  </dl>
</section>

// src/views/Settings.vue
<template>
  <div>
    <section>
      <h1 class="hide-low">Settings</h1>
      <dl>
        <dt v-explain="'settings.backup'"></dt>
        <dd>
          <a v-on:click="onClickDownload($event,'config')" class="btn btn-secondary btn-sm" href="#">config</a>
          <a v-on:click="onClickDownload($event,'data')" class="btn btn-secondary btn-sm" href="#">data</a>
        </dd>
        <dt v-explain="'settings.restore'"></dt>
        <dd>
          <label class="btn btn-secondary btn-sm" for="restore">restore</label><input accept="application/json, text/json, .json" type="file" id="restore" v-on:change="onChangeRestore" class="visually-hidden" />
        </dd>
        <dt v-explain="'settings.clear'"></dt>
        <dd>
          <button v-on:click="onClickClear('config')" class="btn btn-secondary btn-sm">config</button>
          <button v-on:click="onClickClear('data')" class="btn btn-secondary btn-sm">data</button>
        </dd>
      </dl>
    </section>
    <section>
      <dl>
        <dt v-explain="'settings.projectNumberTemplate'"></dt><dd>
          <InterpolationUI v-model="settings.projectNumberTemplate"></InterpolationUI>
        </dd>
        <dt v-explain="'settings.csvTemplate'"></dt><dd>
          <InterpolationUI v-model="settings.csvTemplate"></InterpolationUI>
        </dd>
        <dt v-explain="'settings.langs'"></dt><dd>
          <input v-model="settings.langsJoined" />
        </dd>
        <dt v-explain="'settings.currency'"></dt><dd>
          <select v-model="settings.currency">
            <option v-for="currency in currencies" v-bind:value="currency.code" ngDefaultControl>{{currency.name}} ({{currency.symbol}})</option>
          </select>
        </dd>
        <dt v-explain="'settings.homeMessage'"></dt><dd>
          <label class="checkbox"><input v-model="settings.homeMessage" type="checkbox" /><span></span></label>
        </dd>
      </dl>
    </section>
  </div>
</template>

<script>
import model from '@/model'
import {track,untrack,revert} from '@/formState'
import {CURRENCY_ISO} from '@/config/currencyISO'
import InterpolationUI from '@/components/InterpolationUI'

export default {
  name: 'settings'
  ,data () {
    return {
      settings:{}
      ,currencies: []
    }
  }
  ,components: { InterpolationUI }
  ,mounted(){
    this.settings = track(this.$el,model.config)
    this.currencies = Object.keys(CURRENCY_ISO).map(key=>CURRENCY_ISO[key])
  }
  ,destroyed: untrack
  ,methods: {
    
    onClickDownload(e, type){
      const currentTarget = e.currentTarget
          ,isConfig = type==='config'
          ,dataString = JSON.stringify(isConfig?model.config:model.data)
      currentTarget.setAttribute('href', `data:text/json,${encodeURIComponent(dataString)}`)
      currentTarget.setAttribute('download', `${type}.json`)
    }
  
    ,onChangeRestore(e, type){
      const target = e.target
      const fileReader = new FileReader()
      const file = target.files[0]
      fileReader.readAsText(file)
      fileReader.addEventListener('load', ()=>{
        const result = fileReader.result
            ,resultData = JSON.parse(result)
            ,{type} = resultData
        if (type==='data') {
          model.data = resultData
        } else if (type==='config') {
          model.config = resultData
          revert()
        }
        target.value = null
      })
    }
  
    ,onClickClear(type){
      if (confirm(`Do you really want to clear the ${type}?`)) {
        if (type==='data') {
          model.data = null
        } else if (type==='config') {
          model.config = null
          revert()
        }
      }
    }
    
  }
}
</script>
