// src/app/component/header/header.component.ts
import {Component} from '@angular/core'
import {Router, NavigationEnd} from '@angular/router'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})

export class HeaderComponent {

  public active = 'active'
  public dropped = false

  constructor(private router: Router){
    router.events.subscribe(e => {
      if (e instanceof NavigationEnd) {
        this.dropped = false
      }
    })
  }

}

<header>
  <nav>
    <ul class="list-unstyled list-inline">
      <li>
        <input id="hamburger" type="checkbox" class="visually-hidden" [(ngModel)]="dropped" />
        <label for="hamburger"><span></span></label>
        <ul class="list-unstyled list-inline">
          <li><a routerLink="/" [routerLinkActive]="[active]" [routerLinkActiveOptions]="{exact: true}"><!--<img src="/static/img/logo.svg" /> -->home</a></li>
          <li class="drop">
            <label for="drop1"><a routerLink="/overview" [routerLinkActive]="[active]">overview</a></label>
            <input id="drop1" type="checkbox" class="visually-hidden" />
            <ul>
              <li><a routerLink="/overview/quarter" [routerLinkActive]="[active]">quarter</a></li>
            </ul>
          </li>
          <li><a routerLink="/clients" [routerLinkActive]="[active]">clients</a></li>
          <li class=" drop">
            <label for="drop2"><a routerLink="/settings" [routerLinkActive]="[active]">settings</a></label>
            <input id="drop2" type="checkbox" class="visually-hidden" />
            <ul>
              <li><a routerLink="/data" [routerLinkActive]="[active]">data</a></li>
              <li><a routerLink="/copy" [routerLinkActive]="[active]">copy</a></li>
            </ul>
          </li>
          <li><a routerLink="/about" [routerLinkActive]="[active]">about</a></li>
        </ul>
      </li>
      <li class="buttons">
        <app-saveable-buttons></app-saveable-buttons>
      </li>
    </ul>
  </nav>
</header>

// src/components/Header.vue
<template>
  <header>
    <div class="layout">
      <nav>
        <ul class="list-unstyled list-inline">
          <li>
            <input class="visually-hidden" id="hamburger" type="checkbox">
            <label for="hamburger"><span></span></label>
            <ul class="list-inline">
              <li><router-link to="/">home</router-link></li>
              <li class="drop">
                <label for="drop1"><router-link to="/overview" class="active">overview</router-link></label>
                <input class="visually-hidden" id="drop1" type="checkbox">
                <ul>
                  <li><router-link to="/overview/quarter">quarter</router-link></li>
                </ul>
              </li>
              <li><router-link to="/clients">clients</router-link></li>
              <li class="drop">
                <label for="drop2"><router-link to="/settings">settings</router-link></label>
                <input class="visually-hidden" id="drop2" type="checkbox">
                <ul>
                  <li><router-link to="/layout">layout</router-link></li>
                  <li><router-link to="/data">data</router-link></li>
                  <li><router-link to="/copy">copy</router-link></li>
                </ul>
              </li>
              <li><router-link to="/about">about</router-link></li>
            </ul>
          </li>
        </ul>
      </nav>
      <saveable-buttons class="float-right"></saveable-buttons>
    </div>
  </header>
</template>

<script>
import SaveableButtons from '@/components/SaveableButtons.vue'
export default {
  name: 'AppHeader'
  ,components: {
    SaveableButtons
  }
}
</script>

<style lang="scss" scoped>
  @import '/../variables';
  header {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    z-index: 2;
    padding: $padding/2 0;
    background-color: $colorHeader;
    box-shadow: 0 0 16px $colorHeader;
  }
  .layout {
    display: flex;
    >* { flex: 0 0 auto; }
    nav {
      flex: 1 1 auto;
    }
  }
  ul {
    margin-top: 2px;
  }
  a {
    color: #FFF;
    text-decoration: none;
  }
  .drop {
    position: relative;
    label+input+ul {
      display: none;
    }
    label+input:checked+ul {
      display: block;
      left: 0;
      top: 0;
    }
  }
</style>
