// src/views/Home.vue
<template>
  <div>
    <section v-if="config.homeMessage" class="jumbotron clearfix">
      <p>This invoicing application stores all your data on your local machine.<br/>
      <em><small>Because all your data are belongs to you.</small></em></p>
      <button class="btn-link float-right" v-on:click="onHideWelcome">hide message</button>
      <router-link v-bind:to="'/about'" class="btn btn-link float-right">read more</router-link>
    </section>
    <div class="row no-gutters">
      <section class="col-12 col-md-5">
        <h2>What do you want to do:</h2>
        <p><button v-on:click="onAddClient">Create a new client</button></p>
        <p><button v-on:click="onAddProjectForLatestClient" v-if="latestClient">Create project for '{{latestClient.name}}'</button></p>
        <p><button v-on:click="onCloneLatestProject" v-if="latestProject">Clone project '{{latestProject.description}}'</button></p>
        <p><router-link to="/overview/quarter" class="btn">See current quarter</router-link></p>
      </section>
      <section class="col-12 col-md-7">
        <h2>Open invoices</h2>
        <p v-if="invoices.length===0"><em>You currently have no open invoices... yay!</em></p>
        <project-list v-if="invoices.length>0" :projects="invoices" :cols="'paid date description totalIncDiscounted actions'" :totals="false"></project-list>
      </section>
      <section class="col-12 col-md-7">
        <h2>Draft projects</h2>
        <p v-if="drafts.length===0"><em>You currently have no drafts... :-/</em></p>
        <project-list v-if="drafts.length>0" :projects="drafts" :cols="'clientName description totalIncDiscounted actions'" :totals="false"></project-list>
      </section>
    </div>
  </div>
</template>

<script>
import model from '@/model'
import {save,modelSaved} from '@/formState'
import ProjectList from '../components/ProjectList'
export default {
  name: 'home'
  ,components: {ProjectList}
  ,data () {
    return {
      invoices: []
      ,config: model.config
      ,drafts: []
      ,latestProject: []
      ,latestClient: {}
    }
  }
  ,mounted(){
    this.invoices = model.projects.filter(p=>!p.paid&&p.invoices.length)
    this.drafts = model.projects.filter(p=>p.invoices.length===0)
    this.latestProject = model.projects.sort((a,b)=>new Date(a.dateLatest)>new Date(b.dateLatest)?1:-1).pop()
    this.latestClient = model.getClientByNr(this.latestProject.clientNr)
    console.log('this.latestProject',this.latestProject,this.latestProject.dateLatest); // todo: remove log
  }
  ,methods: {
    onAddClient(){
      const client = model.addClient()
      client && this.$router.push(client.uri)
    }
    ,onAddProjectForLatestClient(){
      const project = this.latestClient.createProject()
      project && save()
      this.$router.push(project.uri)
    }
    ,onCloneLatestProject(){
      console.log('onCloneLatestProject'); // todo: remove log
    }
    ,onHideWelcome() {
      console.log('onHideWelcome',23); // todo: remove log
      this.config.homeMessage = false
      save()
    }
  }
}
</script>

<style lang="scss" scoped>
  @import '../style/variables';
  $bgcolor: #3f5267;
  
  .jumbotron {
    display: block;
    position: relative;
    top: -$padding;
    margin-bottom: 40px;
    font-size: 2rem;
    line-height: 130%;
    background-color: $bgcolor;
    box-shadow:
        1000px 0 0 $bgcolor,
        -1000px 0 0 $bgcolor,
        200px 0 0 $bgcolor,
        -200px 0 0 $bgcolor;
    &, * { color: white; }
    p {
      padding: 40px;
    }
    button, a {
      font-size: 12px;
      line-height: 130%;
    }
  }
  
  section+section {
    margin-top: 0;
    padding-top: 0;
    box-shadow: none;
  }
</style>

// src/app/page/home/home.component.ts
import { Component, OnInit } from '@angular/core'
import {Router} from '@angular/router'
import {ModelService} from '../../model/model.service'
import {Client} from '../../model/client'
import {IProject} from '../../interface/project'
import {INVOICE} from '../../config/invoice'
import {IClient} from '../../interface/client'
import {Project} from '../../model/project'
import {IInvoice} from '../../interface/invoice'
import {IConfig} from '../../interface/config'
import {dateTimeToDate} from '../../mixins'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  static data:any = {
    title: 'Home',
    heading: '',
    meta: {description: 'Welcome to something'}
  }
  config:IConfig
  projects:IProject[] = []
  latestClient:IClient
  latestProject:IProject
  dateFormat:string = INVOICE.dateFormat

  constructor(
      private router: Router,
      public modelService:ModelService
  ) { }

  ngOnInit() {
    this.config = this.modelService.getConfig()
    this.projects = this.modelService.getProjects()
    this.latestClient = this.modelService.getClients().slice(0).sort((client1, client2)=>{
      return (client1 as Client).lastProjectDate>(client2 as Client).lastProjectDate?1:-1
    }).slice(0).pop()
    this.latestProject = this.latestClient&&this.latestClient.projects.slice(0).pop()
  }

  onPaidChange() {
    this.modelService.save()
  }

  onAddReminder(project:Project) {
    let invoices = project.invoices,
        numInvoices = invoices.length
    invoices.push(<IInvoice>{
      date: dateTimeToDate(),
      type: numInvoices===0?'invoice':'reminder', // todo: from const
      interest: false,
      exhortation: false
    })
    this.modelService.save()
    this.router.navigate([project.uri+'/reminder/'+numInvoices])
  }

  onAddClient() {
    let client = this.modelService.addClient()
    this.router.navigate([client.uri])
  }

  onAddProjectForLatestClient() {
    const project = this.modelService.addProject(this.latestClient.nr)
    this.router.navigate([project.uri])
  }

  onCloneLatestProject() {
    if (this.latestProject) {
      const clonedProject = this.modelService.cloneProject(this.latestProject) as Project
      this.router.navigate([clonedProject.uri])
    }
  }

  onHideWelcome() {
    this.config.homeMessage = false
    this.modelService.save()
  }

}
<section *ngIf="config.homeMessage" class="jumbotron">
  <p>This invoicing application stores all your data on your local machine.<br/>
  <em><small>Because all your data are belongs to you.</small></em></p>
  <button class="btn btn-sm btn-link float-right" (click)="onHideWelcome()">hide message</button>
</section>
<div class="row">
  <section class="col-12 col-md-7">
    <h2>Open invoices</h2>
    <p *ngIf="projects.length===0"><em>You currently have no open invoices... yay!</em></p>
    <table *ngIf="projects.length>0">
      <thead><tr>
        <th data-order-key="paid" width="10%">paid</th>
        <th data-order-key="client" width="60%">client</th>
        <th data-order-key="totalIncDiscounted" width="20%">amount</th>
        <th width="20%">actions</th>
      </tr></thead>
      <tbody>
        <tr
            *ngFor="let project of projects | arrayFilter:'!paid' | arraySort:'-timestampLatest' "
            class="row-select ng-scope"
            [ngClass]="{'row-select':true,'alert-paid':project.paid,'alert-late':project.isLate,'alert-pending':project.isPending}"
            title="{{project.invoiceNr}} {{project.date | date:dateFormat}} {{project.description}}"
        >
          <td>
            <label class="checkbox">
              <input [(ngModel)]="project.paid" (change)="onPaidChange()" type="checkbox" /><span></span>
            </label>
          </td>
          <td><a routerLink="{{project.uri}}">{{modelService.getClientByNr(project.clientNr).name}}</a></td>
          <td class="text-right">{{project.totalIncDiscounted | currency:'EUR':true}}</td>
          <td><button (click)="onAddReminder(project)" class="btn btn-sm btn-primary">Add reminder</button></td>
        </tr>
      </tbody>
    </table>
  </section>
  <section class="col-12 col-md-5">
    <p>What do you want to do:</p>
    <p><button (click)="onAddClient()" class="btn btn-primary">Create a new client</button></p>
    <p><button (click)="onAddProjectForLatestClient()" *ngIf="latestClient" class="btn btn-primary">Create project for {{latestClient.name}}</button></p>
    <p><button (click)="onCloneLatestProject()" *ngIf="latestProject" class="btn btn-primary">Clone project {{latestProject.description}}</button></p>
    <p><a routerLink="/overview/quarter" class="btn btn-primary">See current quarter</a></p>
  </section>
</div>
