// src/views/Layout.vue
<template>
  <div>
    <section>
      <header class="clearfix">
        <lang class="float-right"></lang>
        <h1 class="hide-low">Layout</h1>
      </header>
      <print-invoice :client="client" :project="project" :invoice="invoice" :settings="settings"></print-invoice>
    </section>
    <section>
      <dl data-class="row no-gutters">
        
        <dt data-class="name">Theme</dt><dd>
          <select v-model="settings.theme">
            <option v-for="theme in settings.themes" v-bind:value="theme">{{theme}}</option>
          </select>
        </dd>
        
        <dt data-class="name">logo</dt><dd>
          <label class="btn">add image<input accept="image/gif, image/jpg, image/jpeg, image/png, image/svg, .gif, .jpg, .jpeg, .png, .svg" type="file" v-on:change="onChangeLogo" class="visually-hidden" /></label>
          <button v-on:click="onDeleteLogo">delete image</button>
        </dd>
        
        <dt data-class="name colors">Colors</dt><dd>
          <label><input type="color" v-on:change="onChangeVariables" v-model="settings.themeMainBgColor"/>main background</label><br/>
          <label><input type="color" v-on:change="onChangeVariables" v-model="settings.themeMainFgColor"/>main foreground</label><br/>
          <label><input type="color" v-on:change="onChangeVariables" v-model="settings.themeSecondaryBgColor"/>secondary background</label><br/>
          <label><input type="color" v-on:change="onChangeVariables" v-model="settings.themeSecondaryFgColor"/>secondary foreground</label><br/>
        </dd>
    
        <dt class="name font-size"><label for="font-size">base font size</label></dt><dd>
            <input class="form-control" id="font-size" type="range" min="5" max="30" step="0.2" v-model="settings.themeFontSize" v-bind:data-reflect="settings.themeFontSize" v-on:change="onChangeVariables" />
        </dd>
        
        <dt class="name"><label for="font-main">main font</label></dt><dd>
          <select v-model="settings.themeFontMain" v-on:change="onChangeVariables">
            <option v-for="font in fonts" v-bind:value="font.family">{{font.family}}</option>
          </select>
        </dd>
        
        <dt class="name"><label for="font-currency">currency font</label></dt><dd>
          <select v-model="settings.themeFontCurrency" v-on:change="onChangeVariables">
            <option v-for="font of fonts" data-array-filter=" | arrayFilter:'category=monospace'" v-bind:value="font.family">{{font.family}}</option>
          </select>
        </dd>
        
        <dt data-class="name wide">invoiceCSS</dt><dd>
          <textarea class="sass" rows="16" v-model="settings.invoiceCSS" v-bind:change="onChangeSass(settings.invoiceCSS)"></textarea>
        </dd>
      </dl>
    </section>
  </div>
</template>

<script>
import Lang from '@/components/Lang.vue'
import PrintInvoice from '@/components/PrintInvoice.vue'
import model from '@/model'
import defaultData from '@/data/data'
import {create as createClient} from '@/model/client'
import {track,untrack,save,saveable} from '@/formState'
import {sassChanged, cssVariablesChanged} from '@/model/css'

export default {
  name: 'layout'
  ,data () {
    return {
      client:{}
      ,project:{}
      ,invoice:{}
      ,settings:{}
      ,pageReady:false
      ,fonts:[]
    }
  }
  ,mounted(){
    this.client = createClient(defaultData.clients[0]) // get from dummy
    this.project = this.client.projects[0]
    this.invoice = this.project.invoices[0]
    //
    this.settings = track(this.$el, model.config)
    //
    cssVariablesChanged.dispatch(this.settings)
    // todo trigger cssVariablesChanged on revert
    //
    this.getFonts()
  }
  ,components: {
    Lang
    ,PrintInvoice
  }
  ,destroyed: untrack
  ,methods: {
    
    onChangeVariables(){
      cssVariablesChanged.dispatch(this.settings)
    }
  
    ,onChangeSass(sass){
      sassChanged.dispatch(sass)
    }
  
    ,onChangeLogo(e){
      const target = e.target // as HTMLInputElement
      const fileReader = new FileReader()
      const file = target.files[0]
      fileReader.readAsDataURL(file)
      fileReader.addEventListener('load', ()=>{
        const result = fileReader.result
        const img = document.createElement('img')
        img.addEventListener('load', this.onLogoLoad.bind(this, result, img))
        img.setAttribute('src', result)
        target.value = null
      })
    }
  
    ,onDeleteLogo(){
      this.onLogoLoad()
    }
  
    ,onLogoLoad(result, img){
      this.settings.themeLogoCSS = result?`.invoice #logo {
          width: ${img.naturalWidth}px;
          height: ${img.naturalHeight}px;
          background: url(${result}) no-repeat;
      }`:''
      cssVariablesChanged.dispatch(this.settings)
    }
    
    ,getFonts(){
      fetch(`https://www.googleapis.com/webfonts/v1/webfonts?key=${this.settings.googleFontsAPIKey}`)
          .then(response=>response.json())
          .then(result=>{
            this.fonts = result.items
          })
      /*this.restService.load(`https://www.googleapis.com/webfonts/v1/webfonts?key=${this.settings.googleFontsAPIKey}`)
          .then(result=>{
            console.log('resultfonts',result)
            this.fonts = result.items
          })*/
    }
    
  }
}
</script>

// src/app/page/layout/layout.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core'
import {ModelService} from '../../model/model.service'
import {RestService} from '../../service/rest.service'
import {Saveable} from '../../abstract/saveable'

import {IClient} from '../../interface/client'
import {IFont} from '../../interface/font'
import {Client} from '../../model/client'
import {Project} from '../../model/project'
import * as dummyData from '../../dummy/data'
import {sassChanged, cssVariablesChanged} from '../../signals'

@Component({
  selector: 'app-settings',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.scss']
})

export class LayoutComponent extends Saveable implements OnInit, OnDestroy {

  static data:any = {
    title: 'Settings',
    heading: 'Settings',
    meta: {robots: 'noindex, nofollow'}
  }

  settings:any
  client:any
  project:any
  invoice:any

  fonts:IFont[]

  constructor(
      protected modelService:ModelService,
      protected restService:RestService
  ) {
    super(modelService)
  }

  ngOnInit() {
    super.ngOnInit()
    this.settings = this.setModel(this.modelService.getConfig())
    //
    const client = new Client(<IClient>dummyData.default.clients[0])
    client.projects = client&&client.projects.map(project=>new Project(project, client, this.modelService))
    this.client = client
    this.project = client&&client.projects.slice(0).pop()
    this.invoice = this.project.invoices.slice(0).shift()
    //
    this.getFonts()
    //
    sassChanged.dispatch(this.settings.invoiceCSS)
    setTimeout(sassChanged.dispatch.bind(sassChanged, this.settings.invoiceCSS))
  }

  ngOnDestroy(){
    sassChanged.dispatch()
  }

  getFonts(){
    this.restService.load(`https://www.googleapis.com/webfonts/v1/webfonts?key=${this.settings.googleFontsAPIKey}`)
        .then(result=>{
          this.fonts = result.items
        })
  }

  onChangeVariables(){
    // todo: check why this.settings takes one tick to update ngmodel
    setTimeout(cssVariablesChanged.dispatch.bind(cssVariablesChanged, this.settings))
  }

  onChangeSass(sass:string){
    sassChanged.dispatch(sass)
  }

  onChangeLogo(e:Event){
      const target:HTMLInputElement = e.target as HTMLInputElement
      const fileReader = new FileReader()
      const file = target.files[0]
      fileReader.readAsDataURL(file)
      fileReader.addEventListener('load', ()=>{
        const result = fileReader.result
        const img = document.createElement('img')
        img.addEventListener('load', this.onLogoLoad.bind(this, result, img))
        img.setAttribute('src', result)
        target.value = null
      })
  }

  onDeleteLogo(){
    this.onLogoLoad()
  }

  onLogoLoad(result?:string, img?:HTMLImageElement){
    // width: ${img.naturalWidth}px;
    this.settings.themeLogoCSS = result?`.invoice #logo {
    height: ${img.naturalHeight}px;
    background-image: url(${result});
}`:''
    cssVariablesChanged.dispatch(this.settings)
    this.onNgModelChanged()
  }

  onRevert(){
    super.onRevert()
    sassChanged.dispatch()
    setTimeout(cssVariablesChanged.dispatch.bind(cssVariablesChanged, this.settings))
  }

  protected cloneModel():any {
    return this.settings = <any>super.cloneModel()
  }

}


<section class="float-md-right">
  <div class="invoice-shade"><div></div></div>
  <app-print-invoice [client]="client" [project]="project" [invoice]="invoice" [settings]="settings"></app-print-invoice>
  <app-lang class="float-right"></app-lang>
</section>
<section>
  <dl class="row">
    
    <dt class="name">Theme</dt><dd>
      <select class="form-control" [(ngModel)]="settings.theme" (ngModelChange)="onNgModelChanged()">
        <option *ngFor="let theme of settings.themes" value="{{theme}}">{{theme}}</option>
      </select>
    </dd>
    
    <dt class="name">logo</dt><dd>
      <label class="btn btn-secondary btn-sm">add image<input accept="image/gif, image/jpg, image/jpeg, image/png, image/svg, .gif, .jpg, .jpeg, .png, .svg" type="file" (change)="onChangeLogo($event)" class="visually-hidden" /></label>
      <button class="btn btn-secondary btn-sm" (click)="onDeleteLogo()">delete image</button>
    </dd>
    
    <dt class="name colors">Colors</dt><dd>
      <label><input class="form-control" type="color" (ngModelChange)="onNgModelChanged();onChangeVariables()" [(ngModel)]="settings.themeMainBgColor"/>main background</label>
      <label><input class="form-control" type="color" (ngModelChange)="onNgModelChanged();onChangeVariables()" [(ngModel)]="settings.themeMainFgColor"/>main foreground</label>
      <label><input class="form-control" type="color" (ngModelChange)="onNgModelChanged();onChangeVariables()" [(ngModel)]="settings.themeSecondaryBgColor"/>secondary background</label>
      <label><input class="form-control" type="color" (ngModelChange)="onNgModelChanged();onChangeVariables()" [(ngModel)]="settings.themeSecondaryFgColor"/>secondary foreground</label>
    </dd>
    
    <dt class="name colors"><label for="font-size">Base font size</label></dt><dd>
        <input class="form-control" id="font-size" type="range" min="5" max="30" step="0.1"  [(ngModel)]="settings.themeFontSize" (ngModelChange)="onNgModelChanged();onChangeVariables()" />
    </dd>
    
    <dt class="name colors"><label for="font-main">Main font</label></dt><dd>
      <select id="font-main" class="form-control" [(ngModel)]="settings.themeFontMain" (ngModelChange)="onNgModelChanged();onChangeVariables()">
        <option *ngFor="let font of fonts" value="{{font.family}}">{{font.family}}</option>
      </select>
    </dd>
    
    <dt class="name colors"><label for="font-currency">Currency font</label></dt><dd>
      <select id="font-currency" class="form-control" [(ngModel)]="settings.themeFontCurrency" (ngModelChange)="onNgModelChanged();onChangeVariables()">
        <option *ngFor="let font of fonts | arrayFilter:'category=monospace'" value="{{font.family}}">{{font.family}}</option>
      </select>
    </dd>
    
    <dt class="name wide">invoiceCSS</dt><dd>
      <textarea class="sass" rows="16" [(ngModel)]="settings.invoiceCSS" (ngModelChange)="onNgModelChanged();onChangeSass(settings.invoiceCSS)"></textarea>
    </dd>
  </dl>
</section>
